import type { Theme } from "../types/theme";

export const THEMES: Theme[] = [
  {
    id: "electric-cyan",
    name: "Electric Cyan",
    feel: "Modern, encrypted, futuristic.",
    primary: "#00D9FF",
    secondary: "#0099FF",
    background: "#0A0D12",
    surface: "#161B22",
    text: "#F2F6FC",
  },
  {
    id: "emerald-green",
    name: "Emerald Green",
    feel: "Secure, professional, privacy-focused.",
    primary: "#00E676",
    secondary: "#00C853",
    background: "#0B0F0C",
    surface: "#151A16",
    text: "#E8F5EC",
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    feel: "Premium, elegant, AI-inspired.",
    primary: "#8B5CF6",
    secondary: "#6D28D9",
    background: "#0D0A12",
    surface: "#1A1325",
    text: "#F3E8FF",
  },
  {
    id: "crimson-red",
    name: "Crimson Red",
    feel: "Aggressive, stealth, bold.",
    primary: "#FF3B5C",
    secondary: "#D81860",
    background: "#0E090A",
    surface: "#1A0F12",
    text: "#FFE5E9",
  },
  {
    id: "gold-amber",
    name: "Gold / Amber",
    feel: "Luxury, executive, enterprise-grade.",
    primary: "#FFC107",
    secondary: "#FF9800",
    background: "#111111",
    surface: "#1C1C1C",
    text: "#FFF8E1",
  },
  {
    id: "aurora-blue-violet",
    name: "Aurora Blue-Violet",
    feel: "Premium, dynamic, futuristic.",
    primary: "#00E5FF",
    secondary: "#7C4DFF",
    background: "#0A0D16",
    surface: "#141A2A",
    text: "#EAF2FF",
    gradient: "linear-gradient(135deg, #00E5FF 0%, #2979FF 50%, #7C4DFF 100%)",
  },
];
